spring:
  application:
    name: projetS5

  data:
    mongodb:
      uri: mongodb://mongo:27017/boardgames
      database: boardgames

  ai:
    # on force la génération via openai (Groq) et embeddings via ollama
    model:
      chat: openai
      embedding: ollama

    # Embedding local (Ollama)
    ollama:
      base-url: http://ollama:11434
      embedding:
        options:
          model: nomic-embed-text

    # Chat online (Groq via OpenAI compatible)
    openai:
      base-url: https://api.groq.com/openai
      api-key: ${GROQ_API_KEY}
      chat:
        options:
          model: llama-3.1-8b-instant
          temperature: 0.2

server:
  port: 8081

qdrant:
  grpc:
    host: qdrant
    port: 6334
  api-key: ""

rag:
  collection: boardgames
  top-k: 5

wikipedia:
  base-url: https://fr.wikipedia.org/w/api.php
  user-agent: ${WIKI_USER_AGENT}
